webtalk_init -webtalk_dir C:/Users/ekinn/OneDrive/Masaüstü/tel_project/tel_project.sim/sim_1/behav/xsim/xsim.dir/tel_sim_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Jan  4 14:49:14 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "c9dfd53f-c6c7-457b-86fe-7991378ba369" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "b46140e9ee354d74be917d59a86d2445" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "78" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2592 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1500 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6368_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3248312155 -regid "" -xml C:/Users/ekinn/OneDrive/Masaüstü/tel_project/tel_project.sim/sim_1/behav/xsim/xsim.dir/tel_sim_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/ekinn/OneDrive/Masaüstü/tel_project/tel_project.sim/sim_1/behav/xsim/xsim.dir/tel_sim_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/ekinn/OneDrive/Masaüstü/tel_project/tel_project.sim/sim_1/behav/xsim/xsim.dir/tel_sim_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
